
# data center EU's url https://eu1-developer.deyecloud.com/v1.0
# or US's url https://us1-developer.deyecloud.com/v1.0

baseurl = "https://eu1-developer.deyecloud.com/v1.0"
token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6IjBfa3Jzc2FudG9zMThAZ21haWwuY29tXzIiLCJzY29wZSI6WyJhbGwiXSwiZGV0YWlsIjp7Im9yZ2FuaXphdGlvbklkIjowLCJ0b3BHcm91cElkIjpudWxsLCJncm91cElkIjpudWxsLCJyb2xlSWQiOi0xLCJ1c2VySWQiOjEzMDI1ODY1LCJ2ZXJzaW9uIjoxMDAwLCJpZGVudGlmaWVyIjoia3Jzc2FudG9zMThAZ21haWwuY29tIiwiaWRlbnRpdHlUeXBlIjoyLCJtZGMiOiJldSIsImFwcElkIjoiMjAyNDA5MTc1NTM3MDA2IiwibWZhU3RhdHVzIjpudWxsLCJ0ZW5hbnQiOiJEZXllIn0sImV4cCI6MTc3NDE1OTY2NCwibWRjIjoiZXUiLCJhdXRob3JpdGllcyI6WyJhbGwiXSwianRpIjoiOWVlNDU5N2ItMTUzOS00OTdiLThjY2YtNzY0ODYwZGRhYjNkIiwiY2xpZW50X2lkIjoidGVzdCJ9.Yw6PcV4AHYgEmRh9vfAXZ86rPdOt5t6lOmn6xJLLLO9d6uAjOpey4-gdDfVT_A2eA6UN8P4KGD9osLrV9V-CLPNqTiNbDTlMIRMmX0hMwQJHFTkodS_OiCcYHN05XWZCAQXyPRERsKbxaxDL5MPFP40sjgto38CjGCmdDSKn3TqsUDgUzRKh3BhfPRg1vss_meGern7zrkhICldq63-8p8xM4PgXnkAekVbyderTTYFTLqKChs5Xb5MGTxGhwOLoleF8TJwq81lvPJTdToLL9jSST920X_ixqnHqujA4ezkvzlWnyGjp4JplDrFQc18yZaKAgrxIEPKwkHWq1yXmtQ'  # Replace the token, and you cloud get it by obtain_token.py
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'bearer ' + token
}
